name: Build

on:
  push:
    branches:
      - test_java_with_8_3_no_fork
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build all build type and flavor permutations
        run: |
          export JAVA_OPTS="-javaagent:dd-java-agent.jar"
          ./gradlew assemble
        env:
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_KEY }}


  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Run all local screenshot tests (Roborazzi)
        id: screenshotsverify
        continue-on-error: true
        run: ./gradlew assemble
        env:
            GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_KEY }}
